### ISSUE TITLE
Request for Chart view to support time series axis

### ISSUE THREAD

**Issue by garycmartin** [kengruven/strukt-bugs#20]
Currently Chart axis are restricted to using Number type. It would be great to have support for time series axis so you can plot arbitrary timed events correctly spaced on a graph. Great for quickly examining data logs.  FWIW as a workaround, I'm currently generating a Number ID (Add ID) and using it for the x-axis, though this is only really practical when the data is evenly spaced in time.

**Comment by kengruven** [comment]
Agreed, native time series charts would be very useful.  I'll see what I can do.  This seems like it shouldn't be that difficult to implement.

AddID is a good workaround.  Here's a slightly more complex one that can show the shape of non-equally-spaced time data:

    Compute[fn="your_date_field.getTime()",

**Comment by garycmartin** [comment]
Thanks for the compute hint! It doesn't quite work as is for me as converting the date string with Parse String --> Date operator converts the whole day/date correctly but not the time portion (e.g. string 2017-08-30T14:27:40Z ends up as date 2017-08-30T11:00:00.000Z). However, thanks to your hint, I realised I could just use:

```
Compute[fn=Date.parse(my_date_string_field), into="epoch"]
```

Converting the original string directly to the correct epoch seconds. Looks good :)

**Comment by kengruven** [comment]
Strukt 1.4 now allows you to select a Date field for the x-axis.  Also, if you have a field with some Dates and some Numbers, you'll see both (with their respective icons) so you can pick the one you want.

**Comment by garycmartin** [comment]
Fab. Tested. Works great thanks!

**Comment by kengruven** [comment]
Great!
