### ISSUE TITLE
Schema Support for PostgreSQL Databases

### ISSUE THREAD

**Issue by molschimke** [kengruven/strukt-bugs#30]
Our PostgreSQL backend uses multiple database schemas. Please display all entities from all schemas available to the connecting user and add the schema name to the entity name. This is an easy fix to support PostgreSQL schemas which makes Strukt ready to use in an Enterprise context.

**Comment by molschimke** [comment]
Hi Ken, 

1) the best option would be some form of a dir tree (only 2 levels) as most other tools do (I'm assuming you are talking about the table selection step). DirTree helps because I can hide some schemas as a user.

2) Public is only the default on standard installations. You can 1) hide it / give no access to the end user, 2) give priority to another schema (search-path: means that the default becomes another schema with public being just another option)

3) That is up to you and who do you address with your tool: information_schema and pg_catalog are interesting for admins, but not necessarily ordinary users.

Thank you very much,

Mike

**Comment by molschimke** [comment]
And regarding #2: you could omit the schema name of the default schema (but don't assume that is public). If unsure, just leave in.

**Comment by kengruven** [comment]
I've been playing around with this a bit.

The schema name is going to be in its own value.  There's no restriction on Postgres schema names, so smashing it together with the table name would be ambiguous, or add quoting to an ostensibly unquoted value.  Both are counter to the principles of Strukt.

For now, I'm going to skip listing the 2 built-in system schemas.  You can still, of course, query them.

Using a "dirtree" is an interesting idea.  It's similar to #24, which is also about dealing with hierarchies better.  It's also pretty complex to design and implement in the general case, so I'll be giving it some thought.

In the short term, I'll see about making it easier to filter on schema (or any other string value).  That seems like something I need to do, anyway.

**Comment by kengruven** [comment]
Feel free to re-open this if you have any issues getting Postgres schemas to work right!
