### ISSUE TITLE
New version 1.5.6 crash

### ISSUE THREAD

**Issue by hspagnolo** [kengruven/strukt-bugs#31]
Hello,

I have had twice a crash with new version. I am under Mojave. After having selected "Generate range" and clicking on the blank field. Please see log file attached.
Thanks and regards
Henri
[Strukt_2018-10-28-062600_hsp.log](https://github.com/kengruven/strukt-bugs/files/2522560/Strukt_2018-10-28-062600_hsp.log)

**Comment by kengruven** [comment]
Oh, that's bad!  I'm taking a look.

Thanks for the crash log.  That's super helpful.

So far, it looks like an area where Mojave's APIs got stricter, but Apple didn't bother to document the change.  It may be an easy fix for me.

**Comment by hspagnolo** [comment]
Thanks for that, this is appreciated.

**Comment by hspagnolo** [comment]
Hello,
Sorry to ask, but any news on this?
Thanks and regards
Henri

**Comment by kengruven** [comment]
Hi Henri.  I apologize for the silence.  This bug happened to land right at the busiest time of the year for me -- I barely touched a computer for 2 weeks.  I'll have time starting on Monday, so I plan to have a new release of Strukt in the first half of the week.

Sorry for not being more timely with this.

**Comment by hspagnolo** [comment]
Hi Ken, Thanks you for this and sorry for the disturb.

Regards
Henri

**Comment by kengruven** [comment]
No need to apologize!  It's great to have users who push me.

**Comment by kengruven** [comment]
OK, that took *way* longer than it should have, but there is a new version in Apple's app approval queue, with a fix for the particular crash seen in your log.  When you see Strukt "1.6", give it a try and see if it works better for you!

**Comment by hspagnolo** [comment]
Hi Ken,

Thanks for this. As soon as available I will try.

Regards
Henri

**Comment by hspagnolo** [comment]
Hi Ken,

Thanks for the fix, does not crash anymore.

Regards
Henri

**Comment by kengruven** [comment]
Excellent!  Let me know if you have any other trouble with Strukt on Mojave.

**Comment by hspagnolo** [comment]
Hi Ken,

Seems that few operations are not working like with your samples "My dowloadeded PDF" which returns 0 PDF but I have many into the downloads folder. Also the following (see picture below), the result is not at all the same.



Thanks and regards
Henri

**Comment by hspagnolo** [comment]
Me again Ken,

Sorry I forget to mention also that if you add a flag for example "from" and you set the value by pressing enter, then you add flag "to", this one is placed before flag "from", impossible to move from at the first position, the only way is to set the flags starting by the last one.

Thanks and regards
Henri

**Comment by hspagnolo** [comment]
Ken,

Sorry to bother you, but concerning the problem for which I attended a picture, forget, this works, I simply forget to change the x and the y into the graph.

Sorry for that.

Regards
Henri

**Comment by kengruven** [comment]
Hi Henri,

I don't see any pictures here.  It looks like you're using "reply" to GitHub's email notifications, and I guess that doesn't work for attachments.  Sorry.  I've passed on the word to them.

The order of the flags within an operation doesn't matter.  I get that it's nice to be able to put them in an order that makes sense for you, so I'll look into a way to re-order them after you've created them.  Note that "Edit > Insert Flag" (shortcut: `-`) will insert a flag after (to the right of) the cursor.

Please open new issues for other problems you run into, rather than just adding them all to the same report.  I can't keep track of many separate issues in one bug report.

Thanks!
