### ISSUE TITLE
Operation not working and flag ordering

### ISSUE THREAD

**Issue by hspagnolo** [kengruven/strukt-bugs#32]
Hi Ken,

Seems that few operations are not working like with your samples "My dowloadeded PDF" which returns 0 PDF but I have many into the downloads folder.
Also if you add a flag for example "from" and you set the value by pressing enter, then you add flag "to", this one is placed before flag "from", impossible to move from at the first position, the only way is to set the flags starting by the last one.

Thanks and regards
Henri

**Comment by hspagnolo** [comment]
Hi Ken,

No orange badge and I have already added Strukt to the full disk access and also allowing it to control the computer (this is just in case), but no luck.

3 green badges:

[INFO] Starting pipeline
[INFO] Running Spotlight query: kMDItemFSName LIKE[c] "*.pdf"
[INFO] Finished pipeline


Regards
Henri

**Comment by hspagnolo** [comment]
Hi Ken,

I just find now the solution 😀

I go to Strukt Preferences and I delete all the folders which were set ans I reset them again, It works. I do not know why?

Regards
Henri

**Comment by kengruven** [comment]
FYI, as of Strukt 1.7.2, new flags are inserted *after* the cursor, rather than before it.

There's still no way to rearrange the order of flags that have already been set, but of course it makes no difference to the operation.

**Comment by kengruven** [comment]
FYI, flags now insert after the cursor, rather than before it, and it's now possible to rearrange the flags (command-option-arrows).

**Comment by hspagnolo** [comment]
Hi Ken, Great, thanks for the information. Regards. Henri

**Comment by kengruven** [comment]
The latest version of Strukt, 1.7.5, has some more improvements to the security system.  You'll have to re-add the folders you want authorized, but after that, I'm confident it will work!

Please re-open this bug if you have any further trouble with file access in Strukt.
