### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by hspagnolo** [kengruven/strukt-bugs#34]
Hello,

I have updated with the latest version, but when using the List Contacts, I get the following:
[ERROR] You have declined access, so you will not get any contacts.  To reset permissions, type 'tccutil reset AddressBook' in a Terminal window, and restart Strukt.

I have done the reset into the terminal, but nothing has changed. And it is impossible to add manual Strukt into the Contacts access into the System Preferences.

Thanks and regards
Henri

**Comment by kengruven** [comment]
Hmm, that's strange.  It works for me here (though looking back, maybe "tccutil reset AddressBook" isn't the best solution in this case).

I'd like some more information to try to track this down:

 - What version of macOS are you running?
 - Has this worked for you in the past?  Did you happen to notice it stop working with a Strukt upgrade, or a macOS upgrade?
 - Does Strukt appear in the System Preferences (Security & Privacy -> Privacy -> Contacts) list?  Is the checkbox next to Strukt checked?  Does checking that box help?  Or if it's checked, unchecking and then re-checking it?

Thanks for the report!

**Comment by hspagnolo** [comment]
Hi Ken,

Thanks for the reply.

1 : 10.14.2
2 : I do not have use this in the past, so I can't reply.
3 : No, see snapshot attached.

Regards
Henri

**Comment by hspagnolo** [comment]
Thanks Ken,

As soon as available, I will keep you informed.

Regards
Henri

**Comment by hspagnolo** [comment]
Hi Ken,

Me again, I am not a developper (I was long time ago, but long long....), but maybe related to this:

https://developer.apple.com/documentation/contacts/cncontactstore/1402873-requestaccess

Thanks and regards
Henri

**Comment by kengruven** [comment]
Hi Henri!  By my reading of the documentation, it shouldn't be necessary to call that, especially when running on a background thread.  Presenting a (blocking) dialog box is fine with me, which is what it says it will do.  It works that way on both of my Macs.

Interestingly, the corresponding requestAccess() method in EventKit is (according to its documentation) required, and Strukt does call that.  Do the Strukt operations "List Calendars" and "List Calendar Events" work as you expect?  Does the app appear in the Confidentialité list for Calendriers?

I'll add that to my list of things to investigate, anyway.  Thanks for the tip.

**Comment by hspagnolo** [comment]
Hi Ken,
No both functions does not work and Strukt is not listed into the Confidentialité list for Calendars and Contacts. For what I have seen since Mojave is the fact that if an app do not ask to request access (for Contacts, Calendars, Alarms, Photos, etc), then it won't work.

Regards
Henri

**Comment by kengruven** [comment]
I've confirmed that Mojave has made some security-related changes (which seem to be undocumented) that break the Contact and Event operations.  Still looking for a fix.

**Comment by kengruven** [comment]
After much research and experimentation, I found the secret switch I need to make this work in Mojave!  Expect a 1.6.4 update very soon which fixes this.

In my defense, it wasn't in the API documentation, or the release notes, and it doesn't even work the same as the WWDC talks said it would.  This was a pretty crazy one to track down.

**Comment by hspagnolo** [comment]
Hi Ken,

Great that you solved the problem 😀. Will wait the new release.

Regards
Henri

**Comment by hspagnolo** [comment]
Hi Ken,

It works now. Great. Thanks you.

Regards
Henri

**Comment by kengruven** [comment]
Great!  Let me know if there's anything else funny in Mojave that I need to check out.

**Comment by hspagnolo** [comment]
Hi Ken,

I just install the new version from the MAS (1.7.0) and I use Catalina 10.15.4

Every time I press "enter" to validate the data entering, Strukt crash (eg, I add "List Files", then "folder", I type the folder name, then press "enter")

See the crash log.

Thanks and regards
Henri

**Comment by kengruven** [comment]
Hi Henri.  Please open new bug reports for new issues.  Also, I cannot see any crash log.
