### ISSUE TITLE
Copy to Clipboard Operation should not modify output

### ISSUE THREAD

**Issue by raffi-ismail** [kengruven/strukt-bugs#37]
When performing Copy to Clipboard on a named field, all other columns are filtered out. This should not be the case.

**Comment by kengruven** [comment]
I see what you're saying.  Here's some background on why it works the way it does.

For the output operations (like "Copy to Clipboard" and "Write to File"), there's no perfect way to write every data type in text or binary.  (For example, if your field has locations, it'll have to serialize them to copy them as text to the clipboard, so it uses ISO-6709 format.)  The output from these Strukt operations shows the data it actually put on the clipboard, both in terms of which serialization format, and which field.  For plain text, it happens to be a 1:1 transformation, so you just see the field limiting.

I thought this would be useful, but I can see how it would be problematic, too.

For output operations like these, which behavior (or combination of behaviors) do you think would be most useful?

 - Pass all data through with no change?
 - Change the output column to what was actually serialized, and leave all other columns as-is?
 - Pass all data through, and use log entries to indicate if any data needed to be serialized?
 - (Something else I haven't thought of?)

Thanks for writing in!  This should be an easy one to improve.

**Comment by kengruven** [comment]
Another possible idea I just had:

 - A flag to toggle whether the output should be pass-thru, or as-written.

**Comment by raffi-ismail** [comment]
Or you could pass it through a column called "copied"

**Comment by kengruven** [comment]
Hmm, I don't tend to like using arbitrary column names.  Too easy for me to want to open a file with a "copied" column, and confuse myself.

But that does suggest another idea to me.  Suppose there were a flag, like "output", which indicated where to put the serialized data?

 - If it's empty (the default), we just pass through the data without touching it.
 - If it has a new column name (like "copied"), then that field gets the serialized version that actually got saved.
 - If it has the same value as the "field" flag, then it overwrites that field with the serialized version (i.e., what it does now).  (That's actually just case 2 again, of course.  I'm simply observing that this would be flexible enough to emulate today's behavior.)

This convention would work the same on "Copy to Clipboard", "Write to File", and any other output operations Strukt has in the future.

**Comment by kengruven** [comment]
Hello!  I know it’s been forever and a day.  The 1.7 release should make this possible. There is now a flag which lets you say where to put the output text which was actually copied to the clipboard. When it’s not set, the transformed text is simply discarded, so the existing field remains as-is.

I really don’t know how I managed to miss this in the 1.7 release notes.

I’m going to tentatively close this issue now. If it doesn’t work or you can’t accomplish your goals with it as implemented, please feel free to re-open this bug report and I’ll take another look. Thanks!
