### ISSUE TITLE
Additional Credits text barely readable in macOS Dark Mode

### ISSUE THREAD

**Issue by jonwhipple** [kengruven/strukt-bugs#38]
**Strukt** > **About Strukt** > **Additional Credits** opens the box listing licenses and other projects used in Strukt. When displayed with macOS Dark Mode enabled (**System Preferences** > **General** > **Appearance** > _Dark_) the text of each entry is barely legible. When using Light Mode (**System Preferences** > **General** > **Appearance** > _Light_), all displays as expected. Selecting the text reverses the colours out of the system _Highlight color_ (**System Preferences** > **General** > **Appearance** > _Highlight color_).

Changing settings in **System Preferences** > **Accessibility** > **Display** > **Display**
**Invert colors** – approximately the same as switching to light mode, but text is white on translucent white
**Reduce motion** – as expected no effect
**Increase contrast** – no apparent effect
**Reduce transparency** – no apparent effect
**Differentiate without color** – no apparent effect

Strukt 1.6.6
macOS 10.15.4 Catalina

I have not tested setting macOS appearance to _Auto_, although I expect when Dark Mode is activated automatically, this will be the same result.

**Dark Mode**
<img width="809" alt="Additional-Credits--Dark-Mode" src="https://user-images.githubusercontent.com/792196/79679324-d757a680-81b9-11ea-9f74-37b2b551b952.png">
**Light Mode**
<img width="809" alt="Additional-Credits--Light-Mode" src="https://user-images.githubusercontent.com/792196/79679326-dcb4f100-81b9-11ea-9725-1023f7282fb9.png">
**Dark Mode, selected text**
<img width="809" alt="Additional-Credits--Dark-Mode--Selected" src="https://user-images.githubusercontent.com/792196/79679378-711f5380-81ba-11ea-858e-e1cd77c6ad75.png">

**Comment by kengruven** [comment]
Thanks for the report, and the screenshots.

That is strange.  With Strukt 1.7 on macOS 10.14.6 in dark mode, the text in that window is white.  So either I changed something, or Apple did.

I don't seem to have touched that particular view since 1.6.6.  I'll have to do some more investigation.  My Catalina testing is admittedly lacking.

**Comment by jonwhipple** [comment]
Let me know if I can help in any way. Strukt is a cool app.

**Comment by jonwhipple** [comment]
Looks like we're OK now in Catalina

<img width="1457" alt="Strukt-1 7 0" src="https://user-images.githubusercontent.com/792196/80446590-15e11580-88cc-11ea-8123-e6bb1dad760a.png">

- macOS Catalina 10.15.4
- Strukt 1.7.0

**Comment by kengruven** [comment]
Great to hear it's working now!  Thanks for the update.
