### ISSUE TITLE
Support for Redis

### ISSUE THREAD

**Issue by destari** [kengruven/strukt-bugs#41]
I would to be able to use Redis as a source of data. I realize that is has many different ways of querying data, and returns data in a more JSON like format, but even if you supported a pass through command ability to start with and converted all responses to JSON, that would do the trick for most people. Happy to help with tests, examples, etc (even code).

**Comment by destari** [comment]
I'm dumb. :) disregard

**Comment by kengruven** [comment]
Well, that was easy.  :-)  Let me know if there's anything you want to do that it could do better.
