### ISSUE TITLE
Can't save output file

### ISSUE THREAD

**Issue by newtreen** [kengruven/strukt-bugs#47]
Strukt has been working great.  I rebooted my machine, now I can't write files to my ~/Downloads folder.  In the log, it gives me the error "Couldn't move temp file to destination".

**Comment by kengruven** [comment]
Darn.  This is almost certainly an issue with security-scoped bookmarks (which are required by the Mac sandbox).  They've been flakey for me in the past.

In the short term, here's a workaround:

- In Strukt, open the Preferences panel (under the Strukt menu).
- On the Folders tab, click the "+" in the bottom left.
- Navigate to your ~/Downloads folder, and accept.

This will re-authorize the Downloads folder for the current session.

You'll now see the "Downloads" folder twice in your Preferences, and you're free to remove either one (they're identical), or click "Clean Up" to automatically remove one.

I'll take another look at the security system when I have a moment.

**Comment by kengruven** [comment]
Strukt 1.7.5 is now released with improvements to the security system.  You'll have to re-authorize that folder, but after that, it shouldn't cause any more issues.

Please feel free to re-open this bug if it gives you any more trouble.
