### ISSUE TITLE
Minor naming / documentation issue with "Expression"

### ISSUE THREAD

**Issue by tiguchi** [kengruven/strukt-bugs#5]
Here's the situation. I loaded a table of product definitions and wanted to modify each SKU in it following a fixed pattern. I searched repeatedly through the entire list of operation names and descriptions and I could not find anything that would have intuitively solved my problem.

I searched for "modify/replace/change string" or "generate value" and couldn't find anything fitting.

I was thinking that I was stuck here, that I had to export the SKUs into a file and do some regex match and replace magic there.

In an act of desperation I started playing with the "Expression" operation. It wasn't entirely clear to me in the beginning what the snippet of JS code is actually referring to and what it ultimately does. After I played around with it and saw what it does, I also started understanding the description better. I guess that is fine.

The operation name "Expression" strikes me as difficult to find though, and I also believe the way it is set up with its flags doesn't fall into the typical pattern of the other operation types.

Other operations refer to an existing field using the `field` flag or they introduce a new field using another flag such as "Extract String's" `result` flag.

For visual clarity and also for learning I would expect that the output field of the expression operation is a separate flag. Maybe the operation and flags could be renamed as follows:

```
Compute Field: -result=<TargetFieldName> -expression=<JS value expression>
```

**Comment by kengruven** [comment]
That operation has probably been through more renamings and syntax changes than any other!

My reasoning behind "var=expr..." was that it should be easy to type.  But you're right that it's inconsistent, and if that makes it too confusing, then it's not worth saving a couple keystrokes.  No promises, but I'll give it a try myself and see how it works.

I do like "Compute Field" much better than "Expression" -- almost all the operations are verbs, and it'd be nice to be consistent that way.

**Comment by kengruven** [comment]
I've renamed "Expression" to "Compute", and split out the result into its own flag, and made a few other renaming changes for consistency and brevity.  These changes are part of 1.2.

Let me know what you think.  As always, nothing is final.  I gave this some thought, and used it for a bit myself, but I'm willing to be convinced to change it if it's not working.
