### ISSUE TITLE
Parse JSON is too strict

### ISSUE THREAD

**Issue by kengruven** [kengruven/strukt-bugs#9]
It supports {objects} but not [arrays], or atoms.  In these cases, it basically just wipes out the input, which is not cool.  Can I make it more lenient?

**Comment by peterhbr** [comment]
I bought this app for the JSON parsing. I guess I should've waited to see how well it worked because i can't use Strukt at all in its current state.

**Comment by kengruven** [comment]
I'm sorry.  Can you give me a sample of the type of data you're trying to parse?  I can make sure to test that case while I'm improving this.

**Comment by peterhbr** [comment]
No worries! I'm more patient than my comment probably suggested. Very excited to see where Strukt goes. Here's an example of the basic Elasticsearch output I hope to parse (particularly hits.hits._source):

```{
  "took" : 63,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1000,
    "max_score" : null,
    "hits" : [ {
      "_index" : "bank",
      "_type" : "account",
      "_id" : "0",
      "sort": [0],
      "_score" : null,
      "_source" : {"account_number":0,"balance":16623,"firstname":"Bradshaw","lastname":"Mckenzie","age":29,"gender":"F","address":"244 Columbus Place","employer":"Euron","email":"bradshawmckenzie@euron.com","city":"Hobucken","state":"CO"}
    }, {
      "_index" : "bank",
      "_type" : "account",
      "_id" : "1",
      "sort": [1],
      "_score" : null,
      "_source" : {"account_number":1,"balance":39225,"firstname":"Amber","lastname":"Duke","age":32,"gender":"M","address":"880 Holmes Lane","employer":"Pyrami","email":"amberduke@pyrami.com","city":"Brogan","state":"IL"}
    }, ...
    ]
  }
}```

**Comment by kengruven** [comment]
I played around with this a bit, and there's two main issues I see:

- If I take out the `, ...` characters, and add `{` `}` around the whole thing, it does parse.  Is the request, then, to parse snippets of JSON objects, like this?  I'd have to seek ahead in the stream a bit to see if it looks like it's going to be an array [] or an object {} -- tricky, but not impossible.

- If I then add additional "Parse JSON" operations for field=line, then field=hits, then field=hits, then field=_source, the final one doesn't parse -- it looks like that's because (in addition to the above issue again) it expects "," between objects.  (Wikipedia calls this form "[Concatenated JSON](https://en.wikipedia.org/wiki/JSON_Streaming#Concatenated_JSON)".)  That's definitely something I want to support.

**Comment by peterhbr** [comment]
Sorry! I added the "..." to indicate I had truncated the JSON.

The missing outer "{ }" seems to have been lost when pasting the JSON into my comment - they were there in the original.

**Comment by kengruven** [comment]
Strukt 1.2.1 has been released, and it includes an improved "Parse JSON" operation.  Among other changes, there is now a "linewise?" flag that treats each card as its own independent JSON text (rather than combining all the cards together, and treating it as one JSON text).

I made a little video of using it to drill down into the ElasticSearch sample data:

![parsejson](https://user-images.githubusercontent.com/22565/26856510-f5cf00d8-4ad8-11e7-8b7f-c2e7eb9726a0.gif)

I hope this is more useful for you.  Can you give it a try and tell me what you think?

**Comment by kengruven** [comment]
It's been a week, and "Parse JSON" works on the one sample I've seen, so I'm closing this.

Feel free to re-open if you discover any other ways in which it's not flexible enough for parsing your JSON data!
